Made docker-console less sentient

diff --git a/docker-console b/docker-console
--- a/docker-console
+++ b/docker-console
@@ -14,6 +14,11 @@ SUCCESS=0
 ERROR=1
 
 DOCKER_CONSOLE_PORT=42002
+oSTDOUT_OFFSET="    "
+
+SCRIPT_NAME="${0}"
+
+USAGE="${SCRIPT_NAME} <valid host or IPv4 address>"
 
 ################################################################################
 # VARIABLES
@@ -70,40 +75,10 @@ check_command() {
 #
 if [ ${exit_code} -eq ${SUCCESS} ]; then
 
-    for command in awk nc sed uname ; do
+    for command in awk egrep host nc sed ; do
         check_command "${command}"
         let exit_code=${exit_code}+${return_code}
     done
-
-fi
-
-# WHAT: Determine our platform
-# WHY:  Needed later
-#
-if [ ${exit_code} -eq ${SUCCESS} ]; then
-    my_plat=`${my_uname} -s`
-
-    case ${my_plat} in
-
-        Linux)
-            check_command "md5sum"
-
-            if [ ${return_code} -eq ${SUCCESS} ]; then
-                my_md5_command="${my_md5sum}"
-            fi
-
-        ;;
-
-        Darwin)
-            check_command "md5"
-
-            if [ ${return_code} -eq ${SUCCESS} ]; then
-                my_md5_command="${my_md5}"
-            fi
-
-        ;;
-
-    esac
 
 fi
 
@@ -112,39 +87,18 @@ fi
 #
 if [ ${exit_code} -eq ${SUCCESS} ]; then
 
-    while (( "${#}" )); do
-        key=`echo "${1}" | ${my_sed} -e 's?\`??g'`
-        value=`echo "${2}" | ${my_sed} -e 's?\`??g'`
+    if [ "${1}" != "" ]; then 
+        let ipv4_check=`${my_host} "${1}" | ${my_egrep} -ic "has address|domain name pointer"`
 
-        case "${key}" in
+        if [ ${ipv4_check} -eq 0 ]; then
+            err_msg="Invalid host"
+            exit_code=${ERROR}
+        else
+            host="${1}"
+        fi
 
-            --host|--username|--password)
-                key=`echo "${key}" | ${my_sed} -e 's?^--??g'`
-
-                if [ "${value}" != "" ]; then
-                    eval ${key}="${value}"
-                    shift
-                    shift
-                else
-                    echo "${STDOUT_OFFSET}ERROR:  No value assignment can be made for command line argument \"--${key}\""
-                    exit_code=${ERROR}
-                    shift
-                fi
-
-            ;;
-
-            *)
-                # We bail immediately on unknown or malformed inputs
-                echo "${STDOUT_OFFSET}ERROR:  Unknown command line argument ... exiting"
-                exit
-            ;;
-
-        esac
-
-    done
-
-    if [ "${host}" = "" -o "${username}" = "" -o "${password}" = "" ]; then
-        err_msg="Not enough command line arguments detected"
+    else
+        err_msg="Please provide a valid hostname or IPv4 address"
         exit_code=${ERROR}
     fi
 
@@ -154,6 +108,23 @@ fi
 # WHY:  The reason we are here
 #
 if [ ${exit_code} -eq ${SUCCESS} ]; then
-    auth_hash=`echo "${username}:${password}" | ${my_md5_command} | ${my_awk} '{print $1}'`
-    echo "${auth_hash}" | ${my_nc} ${host} ${DOCKER_CONSOLE_PORT}
+    ${my_nc} ${host} ${DOCKER_CONSOLE_PORT}
 fi
+
+# WHAT: Complain if necessary and exit
+# WHY:  Success or failure, either way we are through
+#
+if [ ${exit_code} -ne ${SUCCESS} ]; then
+
+    if [ "${err_msg}" != "" ]; then
+        echo
+        echo -ne "${STDOUT_OFFSET}ERROR:  ${err_msg} ... processing halted\n"
+        echo
+    fi
+
+    echo
+    echo -ne "${STDOUT_OFFSET}USAGE:  ${USAGE}\n"
+    echo
+fi
+
+exit ${exit_code}
